version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "i-want-to-be-a-unicorn"
s3_prefix = "i-want-to-be-a-unicorn"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
